name: Publish Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Create .pypirc file
        run: |
          cat <<EOF > ~/.pypirc
          [distutils]
          index-servers = 
              pypi

          [pypi]
          repository: https://pypi.pkg.github.com/${{ github.repository_owner }}
          username: __token__
          password: ${{ secrets.PASSWORD }}
          EOF

      - name: Publish package to GitHub Packages
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          twine upload --repository pypi dist/*