name: Publish Package to GitHub Packages

on:
  release:
    types: 
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
            password: ${{secrets.PASSWORD}}
        env:
            TWINE_USERNAME: __token__
            TWINE_REPOSITORY_URL: https://pypi.pkg.github.com/${{github.repository_owner}}